# Generated by Django 3.2.4 on 2021-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='top_subtitle',
            field=models.CharField(default=1, max_length=200, verbose_name='TOPページサブタイトル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='top_title',
            field=models.CharField(max_length=100, verbose_name='TOPページタイトル'),
        ),
    ]
